export const IPTV_EPG_REFRESH_COOLDOWN_SEC = 30;
export const IPTV_CHANNELS_REFRESH_COOLDOWN_SEC = 60;
export const IPTV_EPG_ADMIN_COOLDOWN_SEC = 10;
export const IPTV_CHANNELS_ADMIN_COOLDOWN_SEC = 30;

export const IPTV_EPG_REFRESH_WINDOW_MS = IPTV_EPG_REFRESH_COOLDOWN_SEC * 1000;
export const IPTV_CHANNELS_REFRESH_WINDOW_MS = IPTV_CHANNELS_REFRESH_COOLDOWN_SEC * 1000;
export const IPTV_EPG_ADMIN_WINDOW_MS = IPTV_EPG_ADMIN_COOLDOWN_SEC * 1000;
export const IPTV_CHANNELS_ADMIN_WINDOW_MS = IPTV_CHANNELS_ADMIN_COOLDOWN_SEC * 1000;
